initial ifc check

diff --git a/nw-watchdog b/nw-watchdog
--- a/nw-watchdog
+++ b/nw-watchdog
@@ -388,6 +388,7 @@ $FMT<<EOU
         $_b_%{STATE}$__ - the state of the alert:
         - ${_b_}ERROR$__ for permanent errors
         - ${_b_}WARNING$__ for things that might need reconfiguration
+	- ${_b_}INITIAL$__ for intital problems that needs to be resolved before proceeding
         - ${_b_}DOWN$__ for lost conenctivity to ${___}TARGET${__}
             (will not be fired if already in DOWN, UNREACHABLE or LINKDOWN state)
         - ${_b_}UNREACHABLE$__ for lost conenctivity to NEXTHOP (implies DOWN)
@@ -1042,15 +1043,16 @@ log() {
         printf "%s\n" "$logentry"
     fi
 }
-ALERTSTATE='initial'
+ALERTSTATE='INITIAL'
 alert() {
     [ $V -ge 3 ] || return
     STATE="$1"; shift
 
-    # Do not log or alert initial or repeated UP/DOWN/REACHABLE/UNREACHABLE/LINKDOWN states
-    [ "$ALERTSTATE" = "initial" ] && { [ "$STATE" = "UP" -o "$STATE" = "REACHABLE" -o "$STATE" = "LINKUP" ] && return ;}
-    [ "$STATE" = "ERROR" -o "$STATE" = "WARNING" ] || {
-        [ "$STATE" = "$ALERTSTATE" ] && return                                # No change
+    [ "$STATE" = "ERROR" -o "$STATE" = "WARNING" -o "$STATE" = "INITIAL" ] || { # always alert on ERROR, WARNING and INITIAL
+	[ "$ALERTSTATE" = "INITIAL" ] && {                                    	# Do not alert if we are up after INITIAL
+	    [ "$STATE" = "UP" -o "$STATE" = "REACHABLE" -o "$STATE" = "LINKUP" ] && return
+	}
+        [ "$STATE" = "$ALERTSTATE" ] && return                                # Same state 
         [ "$ALERTSTATE" = "LINKDOWN" -a "$STATE" = "DOWN" ] && return         # LINKDOWN implies DOWN
         [ "$ALERTSTATE" = "LINKDOWN" -a "$STATE" = "UNREACHABLE" ] && return  # LINKDOWN implies UNREACHABLE
         [ "$ALERTSTATE" = "UNREACHABLE" -a "$STATE" = "DOWN" ] && return      # UNREACHABLE implies DOWN
@@ -1170,7 +1172,11 @@ linkcheck() {
         }
         NOLINK=$((NOLINK+1))
         [ $MAXNOLINK -gt 0 -a $NOLINK -gt $MAXNOLINK ] && {
-            alert LINKDOWN "Link down on interface '%s' after $MAXNOLINK reset attempts (with $GRACE seconds in between)!" "$IFC"
+            ip link show $IFC>/dev/null 2>&1 || {
+		alert LINKDOWN "Interface '%s' ... device does not exist after $MAXNOLINK attempts to bring it up!" "$IFC"
+		return 2
+	    }
+	    alert LINKDOWN "Link down on interface '%s' after $MAXNOLINK reset attempts (with $GRACE seconds in between)!" "$IFC"
             return 1
         }
         info "No link on $IFC... reset attempt $NOLINK out of $MAXNOLINK (0=infinite)"
@@ -1406,12 +1412,77 @@ debug "\n\t%s\n\t%s\n\t%s\n\t%s\n\t%s\n\t%s\n\t%s\n\t%s\n\t%s\n\t%s\n\t%s\n\t%s\
       "IFCDOWNT='$IFCDOWNT'" \
       "ALERTCMDT='$ALERTCMDT'"
 
+TADDR=''
+[ -n "$IFC" ] && {
+    IFCUP=`printf "%s" "$IFCUPT" | sed -E "s/\%\{IFC\}/$IFC/g"`
+    IFCDOWN=`printf "%s" "$IFCDOWNT" | sed -E "s/\%\{IFC\}/$IFC/g"`
+
+    ip link show $IFC>/dev/null 2>&1 || { # device does not exist
+	if [ -n "$IFCUPDOWN" ]; then
+	    info "Interface '%s' is not available (no such device), trying to bring it up." "$IFC"
+	    sh -c "$IFCUP" >/dev/null 2>&1
+	    trace "Sleeping for $GRACE seconds."
+	    sleep $GRACE
+	    if [ -n "$STATICIFC" ]; then
+		ip link show $IFC >/dev/null 2>&1
+		while [ $? -ne 0 ]; do
+		    warn "--force-interface '%s' not available (no such device), will keep trying to bring it up.\n\t%s" "$IFC" \
+			 "... or you might want to check your options and restart this instance with correct ones if wrong."
+		    sh -c "$IFCUP" >/dev/null 2>&1
+		    trace "Sleeping for $GRACE seconds."
+		    sleep $GRACE
+		    ip link show $IFC >/dev/null 2>&1
+		done
+	    elif ip link show $IFC >/dev/null 2>&1; then
+		if ip link show $IFC | grep -oq 'state DOWN'; then
+		    alert INITIAL "Initial interface '%s' brought up, but has no link, will continue detecting topology ..." "$IFC"
+		else
+		    info "Interface '%s' brought up successfully." "$IFC"
+		fi
+	    else
+		alert INITIAL "Initial interface '%s' could not be brought up (no such device), will continue detecting topology without it ..." "$IFC"
+		while [ -z "$TADDR" ]; do
+		    resolve_target || {
+			warn "Target '%s' does not resolve to an IPv4 address. Make sure name resoloution funtions on the system\n\t%s\n\t%s" \
+			     "$TARGET" \
+			     '... or stop this instance and start it again using a valid hostname / FQDN or IP address' \
+			     "... sleeping for $GRACE seconds."
+			sleep $GRACE
+		    }
+		done
+		while [ ! nexthop ]; do
+		    warn "--force-interface '%s' could not be brought up (no such device)\n\tand no route to target '%s' (%s) available,\n\t%s\n\t%s\n\t%s" \
+			 "$IFC" "$TARGET" "$TADDR" \
+			 'will keep trying until an interface via which we have a next hop to target is brought up,' \
+			 '... or you might want to check your options and restart this instance with correct ones if wrong.' \
+			 "... sleeping for $GRACE seconds."
+		    ip link show $IFC >/dev/null 2>&1 || sh -c "$IFCUP" >/dev/null 2>&1
+		    trace "Sleeping for $GRACE seconds."
+		    sleep $GRACE
+		done
+	    fi
+	elif [ -n "$STATICIFC" ]; then
+	    while ! ip link show $IFC >/dev/null 2>&1; do
+		warn "--force-interface '%s' is not available (no such device),\n\t%s\n\t%s\n\t%s\n\t%s" "$IFC" \
+		     'and ---no-interface-reset prevents bringing it up,' \
+		     'make sure the interface comes up,' \
+		     '... or you might want to check your options and restart this instance with correct ones if wrong.' \
+		     "... sleeping for $GRACE seconds."
+		sleep $GRACE
+	    done
+	else
+    	    alert INITIAL "Initial interface '%s' is not available (no such device),\n\t%s\n\t%s" "$IFC" \
+		  'and ---no-interface-reset prevents bringing it up!' \
+		  'Detecting topology without initial interface.'
+	fi
+    }
+}
+
 debug "Resolving, or if already IP address, cleaning zero-padding of, target '%s'" "$TARGET"
 # Clean up zero-padding if TARGET is an IP address
 printf "%s" "$TARGET" | grep -qE '^((0*[0-9]?[0-9]|1[0-9][0-9]|2([0-4][0-9]|5[0-5]))\.){3}(0*[0-9]?[0-9]|1[0-9][0-9]|2([0-4][0-9]|5[0-5]))$' \
     && TARGET=`printf "%s" "$TARGET" | sed -E 's/(^|\.)0+([1-9]+)/\1\2/g'`
 
-TADDR=''
 while [ -z "$TADDR" ]; do
     resolve_target || {
         warn "Target '%s' does not resolve to an IPv4 address. Make sure name resoloution funtions on the system\n\t%s\n\t%s" \
@@ -1423,16 +1494,7 @@ while [ -z "$TADDR" ]; do
 done
 
 if [ -n "$IFC" ]; then
-    IFCUP=`printf "%s" "$IFCUPT" | sed -E "s/\%\{IFC\}/$IFC/g"`
-    IFCDOWN=`printf "%s" "$IFCDOWNT" | sed -E "s/\%\{IFC\}/$IFC/g"`
-    nexthop || {
-        linkcheck && {
-            nexthop || {
-                ifreset
-                nexthop
-            }
-        }
-    }
+    nexthop || { linkcheck && { nexthop || { ifreset && nexthop ;};};}
 else
     nexthop
     EXITCODE=$?
@@ -1447,7 +1509,6 @@ else
     done
 fi
             
-
 while true; do
     if [ -n "$PINGTARGET" ]; then
         trace "Continuously checking if target is up..."
