improved help and examples

diff --git a/nw-watchdog b/nw-watchdog
--- a/nw-watchdog
+++ b/nw-watchdog
@@ -305,7 +305,7 @@ $FMT<<EOU
     	Default: '$ALERTCMD'
         Command(s) to which the errors, warnings and alerts messages will be piped, executed with 'sh -c'.
 	%{IFC} will be dynmaically replaced with the interface name currently in use as source interface.
-	Set to '-' to disable alerting (alerts will still be logged if --log-level is 3 or higher).
+	Set to '-' to disable alerting (alerts will still be logged if --verbosity-level is 3 or higher).
 
 	Example of howto email the alert messages using mailx (mailutils) with a custom from address:
 	    --alert='mailx -a 'From: nwwatchdog@this.hst' -s "nwwatchdog alert" my@email.adr'
@@ -346,49 +346,45 @@ ${_b_}EXAMPLES$__
               --ifcup='ipsec up connection-name ; ip tunnel add $IFACE mode vti local 4.3.2.1 remote 1.2.3.4 ttl 255 key 111 ; ip....
 
 
-	Here's an more extensive example of how one can use $nwwatchdog to setup and monitor a wireguard full tunnel, also monitoring the connectivity to the wireguard server, running both whatchdogs as systemd services:
+	Here's an more extensive example of how one can use $nwwatchdog to setup and monitor a wireguard full tunnel, also monitoring the connectivity to the wireguard server, running both whatchdogs as systemd services getting alerts via e-mail:
 
-	Firstly, we setup the monitor for the wireguard server which we reach via the default route:
+	Firstly, we setup the nw-watchdog systemd service for the wireguard server connection which we reach via the default route:
 
 	$_b_$nwwatchdog$__ wgserver.domain.dom \\
 EOU
     cat<<'EOU'
-          --log-level=alert \
-	  --alert='mailx -a "From: nwwatchdog@`cat hostname -f`" -s "wgserver via %{IFC}" admin@`cat /etc/mailname`' \
+          --verbosity-level=3 \
+	  --alert='mailx -a "From: nwwatchdog@`hostname -f`" -s "wgserver via %{IFC}" admin@`cat /etc/mailname`' \
 	  --slow-up-timeout=3 \
 	  --ifup-grace=20 \
-	  --install-systemd=nwwatchdog-wgserver
+	  --install-systemd=wgserver
 EOU
     $FMT<<EOU
 
-	Then we setup the monitor for the wireguard full tunnel which will also create and configure the tunnel:
-	OBSERVE that we, as ${___}TARGET$__, use the actual gw and peer for the subnet (1.0.0.1) and therefore we don't need to ping-check the ${___}TARGET$__ (--no-ping-target) as it will be checked as nexthop.
-
-	It might have been smoother to use some scripts for the ifcup and ifcdown options, but as it's not really necessary we just specify the commands directly as arguments to the options, however for readability there are line-breaks in the command string which should be removed running it. The point is to show that you can do extensive work in the ifcup and ifcdown options.
+	Then we setup the monitor for the wireguard full tunnel which will also create and configure and bring the tunnel up (if not already) upon start of the sytemd service, making sure we have a /32 routes to all of the wireguard server's ip addresses that the hostname resolves to.
+	Note: It would be smoother to use a script and --ifcup=/path/script, but it can also be done like this:
 
 	$_b_$nwwatchdog$__ 10.0.0.1 \\
 EOU
     cat<<'EOU'
-	  --no-ping-target \
-	  --log-level=alert \
-	  --alert='mailx -a "From: nwwatchdog@`cat hostname -f`" -s "wireguard wg0" admin@`cat /etc/mailname`' \
+	  --verbosity-level=3 \
+	  --alert='mailx -a "From: nwwatchdog@`hostname -f`" -s "wireguard wg0" admin@`cat /etc/mailname`' \
 	  --force-interface=wg0 \
 	  --ifcup='ip link add wg0 type wireguard ;
                    ip link set wg0 up ;
                    wg setconf wg0 /etc/wireguard/wg0.conf ;
                    ip address add 10.0.0.2 peer 10.0.0.2 dev wg0 ;
-	           host wgserver.domain.dom
-		     | grep " has address "
-                     | cut -d" " -f4
-                     | while read addr; do
-                         ip route add $addr/32 via `ip route show default | head -1 | cut -d" " -f3` ;
-                       done ; 
-                     ip route add 0.0.0.0/1 via 10.0.0.1 dev wg0 src 10.0.0.2 ; 
-		     ip route add 128.0.0.0/1 via 10.0.0.1 dev wg0 src 10.0.0.2 2>/dev/null' \
+	           getent ahostsv4 wgserver.my.dom | grep -oE "^[0-9.]+" | uniq
+                   | while read addr; do
+                       ip route add $addr/32 via `ip route show default | head -1 | cut -d" " -f3` ;
+                   done ; 
+                   ip route add 0.0.0.0/1 via 10.0.0.1 dev wg0 src 10.0.0.2 ; 
+		   ip route add 128.0.0.0/1 via 10.0.0.1 dev wg0 src 10.0.0.2 2>/dev/null' \
           --ifcdown='ip link del wg0' \
-	  --install-systemd=nwwatchdog-wg0     
+	  --install-systemd=wg0     
 EOU
     $FMT<<EOU
+    $___${_b_}OBSERVE$__ that the entire --ifcup='...' command need to be on a single line without line breaks (linebreaks added here for readability).
 
 ${_b_}DEPENDENCIES$__
         $nwwatchdog depends on the below executables being available in "/sbin:/bin:/usr/sbin:/usr/bin:\$PATH" or being shell-builtin. A check is done at startup and if any of these tools are missing, $nwwatchdog will exit with an error telling which are lacking.
@@ -399,23 +395,23 @@ EOU
     done
     $FMT<<EOU
 
-        If certain utilities are available $_b_$nwwatchdog$__ will use them to enhance its functionality, these are:
+        $_b_$nwwatchdog$__ will function without the below listed utilities, but will use them to enhance its functionality if available.
 
 	- ${_b_}flock$__
             If available the logfile will be locked before truncated or written to.
 	    If not available, there is a slight risk of loglines being lost if two or more instances of $_b_$nwwatchdog$__ are concurently running using the same logfile and at least one of them have $_b_--logsize$__ set to a value larger than 0.
 
 	- ${_b_}wall$__
-	If available it will be used as default $_b_--alert$__ command and otherwise alerting will be done to stderr by default.
+	If available it will be used as default $_b_--alert$__ command. Otherwise, alerting will be done to stderr by default.
 
 	- ${_b_}tput$__
-	Is used to determine the terminal width and output bold and underlined text in this help message if available.
+	Is used to determine the terminal width and output bold and underlined text in this help page.
 
 	- ${_b_}fmt$__
 	Is used to format the help message if available.
 
-	- ${_b_}less$__ or ${_b_}more$__
-	Are used to page the help message if available.
+	- ${_b_}less$__ (or ${_b_}more$__)
+	Is used to page this help.
 
 EOU
     [ -n "$1" ] && printf "$@"
@@ -520,7 +516,7 @@ while [ $# -gt 0 ]; do
 	    if [ "$ARG" = "-z" -o "$ARG" = "--logsize" ]; then LOGSIZE="$1"; shift
 	    elif printf "%s" "$ARG" | grep -qEe '-(-logsize|z)=.*' ; then LOGSIZE="${ARG#*=}"
 	    else LOGSIZE=`printf "%s" "$ARG" | sed -E 's/-(-logsize|z)//'`; fi
-	    printf "%s" "$LOGSIZE" | grep -iqE '^[1-9]+[0-9]*[KMG]*$' || dieUSAGEpager "Invalid logsize '$LOGSIZE'"
+	    printf "%s" "$LOGSIZE" | grep -iqE '^[0-9]+*[KMG]*$' || dieUSAGEpager "Invalid logsize '$LOGSIZE'"
 	    xLOGSIZE=1
 	    ;;
 	-p*|--pidfile*)
@@ -706,27 +702,6 @@ debug() {
     log "  DEBUG: $PATN" "$@"
 }
 
-debug "Resolving, or if already IP address, cleaning zero-padding of, target '%s'" "$TARGET"
-# Clean up zero-padding if TARGET is an IP address
-printf "%s" "$TARGET" | grep -qE '^((0*[0-9]?[0-9]|1[0-9][0-9]|2([0-4][0-9]|5[0-5]))\.){3}(0*[0-9]?[0-9]|1[0-9][0-9]|2([0-4][0-9]|5[0-5]))$' \
-    && TARGET=`printf "%s" "$TARGET" | sed -E 's/(^|\.)0+([1-9]+)/\1\2/g'`
-resolve_target() {
-    trace "Resolving target '%s' (cached='%s')" "$TARGET" "$TADDR"
-    TADDR=`getent ahostsv4 "$TARGET" | head -1 | sed -E 's/^\s*([0-9.]+)\s.*/\1/'`
-    [ -n "$TADDR" ] || return 1
-    trace "Resolved target '%s' to '%s'" "$TARGET" "$TADDR"
-    return 0
-}
-TADDR=''
-while [ -z "$TADDR" ]; do
-    resolve_target ||
-	warn "Target '%s' does not resolve to an IPv4 address. Make sure name resoloution funtions on the system\n\t%s\n\t%s" \
-	     "$TARGET" \
-	     '... or stop this instance and start it again using a valid hostname / FQDN or IP address' \
-	     "... sleeping for $GRACE seconds."
-    sleep $GRACE
-done
-
 ifreset() {
     [ -n "$IFCUPDOWN" ] || {
 	info 'Not resetting interface due to --no-interface-reset.'
@@ -873,6 +848,14 @@ EOF
 
 }
 
+resolve_target() {
+    trace "Resolving target '%s' (cached='%s')" "$TARGET" "$TADDR"
+    TADDR=`getent ahostsv4 "$TARGET" | head -1 | sed -E 's/^\s*([0-9.]+)\s.*/\1/'`
+    [ -n "$TADDR" ] || return 1
+    trace "Resolved target '%s' to '%s'" "$TARGET" "$TADDR"
+    return 0
+}
+
 isup() {
     local ADDR="$1"
 
@@ -979,6 +962,21 @@ debug "\n\t%s\n\t%s\n\t%s\n\t%s\n\t%s\n\t%s\n\t%s\n\t%s\n\t%s\n\t%s\n\t%s\n\t%s\
       "IFCUPT='$IFCUPT'" \
       "IFCDOWNT='$IFCDOWNT'" \
       "ALERTCMD='$ALERTCMD'"
+
+debug "Resolving, or if already IP address, cleaning zero-padding of, target '%s'" "$TARGET"
+# Clean up zero-padding if TARGET is an IP address
+printf "%s" "$TARGET" | grep -qE '^((0*[0-9]?[0-9]|1[0-9][0-9]|2([0-4][0-9]|5[0-5]))\.){3}(0*[0-9]?[0-9]|1[0-9][0-9]|2([0-4][0-9]|5[0-5]))$' \
+    && TARGET=`printf "%s" "$TARGET" | sed -E 's/(^|\.)0+([1-9]+)/\1\2/g'`
+
+TADDR=''
+while [ -z "$TADDR" ]; do
+    resolve_target ||
+	warn "Target '%s' does not resolve to an IPv4 address. Make sure name resoloution funtions on the system\n\t%s\n\t%s" \
+	     "$TARGET" \
+	     '... or stop this instance and start it again using a valid hostname / FQDN or IP address' \
+	     "... sleeping for $GRACE seconds."
+    sleep $GRACE
+done
 
 if [ -n "$IFC" ]; then
     IFCUP=`printf "%s" "$IFCUPT" | sed -E "s/\%\{IFC\}/$IFC/g"`
